### ISSUE TITLE
How to avoid a mass rerendering of everything that depends on only unchanged parts of a State object? 

### ISSUE THREAD

**Issue by szalapski** [TimeWarpEngineering/timewarp-state#266]
Anytime a handler mutates the state, any component that gets state properties and inherits from `BlazorStateComponent` will automatically rerender.  Right?

So that means that any component that depends on one _part_ of that state but not another part will still rerender regardless of what part of the state they need.  In other words, if my component shows `MyState.A` but not `MyState.B`, and there is a change to `MyState.B`, my component will rerender even though it doesn't need to.  

 Suppose I enable a rather complex domain object to be edited piecemeal.  So the user might edit a `CommentsPanel` that internally uses `CurrentOrderState.OrderComments` and a `RushShippingPanel` that internally uses `CurrentOrderState.IsRushShipping`, along with dozens of other properties.  So now any change anywhere in the state will result in dozens of components being rerendered when it is more desirable that only one part at a time needs to be rerendered.  **Is there any way to get more granular with rerendering of components that inherit from `BlazorStateComponent`?**  It strikes me that rerendering everything that depends on a state object when anything in that state object changes (because it's a whole new state each time) is a very blunt approach.

I am thinking there should be a way to avoid rerendering for unchanged parts of the state, as it is inevitable that even the simplest properties on a state object will themselves have properties, many of which won't change. 

_Side note: I am using the term "rerender" for the process by which .NET (in WebAssembly) **runs the C# code** to figure out the overall presentation state of each component in memory.  After that, `OnAfterRender` is called, then manipulating the DOM is a subsequent process.  I try to avoid using the term "render" to mean "manipulating the DOM", since [it seems Microsoft uses it to mean running the C# code](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-5.0)._

For pages of significant scope, rerendering can be the source of much slowness.  If I am showing a 30x10 cell table, and each cell has 1-3 components in it, it can be quite burdensome to rerender (run the C# code to determine what the DOM should become) hundreds of components.  So it would be nice if there was a way to avoid rerendering a component if the **parts** of the state it depends on have not changed.  [I have written a small package to do this _apart from state management_](https://github.com/szalapski/BlazorRerenderReducers), but I was hoping that changes due to state management wouldn't need such a thing (nor do I see a way to make them collaborate together).

Vue and React seem to automagically handle this (I think internally they compare previous state to new state on a per-property basis), but not so with Blazor (hence the need for StateHasChanged at all).

**Comment by szalapski** [comment]
FYI, I am also exploring [the same concern with the Fluxor library](https://github.com/mrpmorris/Fluxor/issues/220).

**Comment by StevenTCramer** [comment]
Currently the subscription is generically placed at the state level.  So we break up States into smaller pieces but yes a complex object that is all in one state would re-render all.  Now we can easily fix the rendering problem by making the subscription more specific to the property.  But doing so also removes the simplicity of automatic subscriptions.

I have not yet run into the scenario where I have found that required. If you have something you could share as a decent test case that would be awesome.

**Comment by szalapski** [comment]
Suppose I have a single-page app that might want state management to store the possible filter values for each of serveral fields in an advanced search, and the current value of each field, and the current search results, and the currently selected item in the search results, and whether that item's detail is currently being shown.  One component might show several of these pieces and another compnoent will show some of them as well as oterhs  I think you would suggest I break up this into several states, and I agree...but I want to be able to have a single master state object where I can use Intellisense to find what I want in the state, so I can go State.Filters.DateRange.AllValues or State.SearchResults.First() or State.CurrentItem.Id.  

Now for example, say I have an action that toggles a boolean on one of the search results, (State.SearchResults[42].IsSelected) and the only thing in the whole state that renders differently based on that boolean value is one component in the several dozen used to show that component.

 Ideally, any change to the state would not cause a rerender of thousands of components I am showing nor even the dozens for this item, but only the one that actually shows a check mark or a frowny face for State.SearchResults[42].IsSelected's value.  Ideally, I want to specify it at any level down the tree of objects in the state. so that other items in the collection don't rerender.

**Comment by StevenTCramer** [comment]
This can be done.  But is not trivial.  I will ad it to my back log.

**Comment by szalapski** [comment]
Great...I wish I could help but in investigating your code, it isn't obvious to me how to do this.

I really want to avoid "registering" which parts of a state object a component depends on.  Ideally, my component would just use the Getters naturally, and Blazor-State via BlazorStateComponent somehow would... 

1. Know which parts of the state have changed
2. Know which parts of the state are referenced by the component (either in markup or in @code)
3. Call StateHasChanged **only** if there is any property that is in both 1 and 2

(Enabling collection item changes too might be a further enhancement, but I'm happy to  limit the scope to property sets for now)

**Comment by StevenTCramer** [comment]
Screen sharing session is a good idea, Please join the discord server and lets discuss more. https://discord.gg/A55JARGKKP

**Comment by szalapski** [comment]
As discussed on Discord, here's a minimal demo of the rerendering issue #266 that I would like to help make nuanced: https://szalapski.github.io/BlazorRerenderReducers/blazor-state-demo
And here's the code: https://github.com/szalapski/BlazorRerenderReducers/tree/main/Sz.BlazorRerenderReducers/Client/BlazorStateDemo

**Comment by StevenTCramer** [comment]
I have not forgotten about this.  Need to get to it.

**Comment by szalapski** [comment]
Want to set a date to look into it together? Contact me in a private
message, via linkedin perhaps.

**Comment by zewa666** [comment]
React classes handle these cases with ShouldComponentUpdate returning a boolean. Perhaps something like that could be added to the base component and called [https://github.com/TimeWarpEngineering/blazor-state/blob/c2dee1fa4e84b614f40e98ddda8e57a9eab04e19/Source/BlazorState/Subscriptions.cs#L100](here) before firing rerendering

**Comment by petersondrew** [comment]
The only workaround I've had for this is to try and separate my stores as much as I can and copy data that's shared between them only when that data updates.

I think a ShouldUpdate would be really helpful since Blazor doesn't have it OOTB (at least not how it is in React). I bet CloneState could be utilized to pass the original and changed state.

We could possibly automate that (maybe in an opt-in fashion) by subscribing to individual store properties rather than the store a a whole? Whatever props are subscribed to could be automatically compared in a base ShouldUpdate method.

**Comment by zewa666** [comment]
well coming from rxjs you could `pluck` the values using the dot notation `state.person.address.street` to only get a slice of the state back. with rxjs and same with rx a distinctUntilChanged would achieve the partial slice change detection. I guess something similar, 2nd param to subscribe, could be realized with this lib as well

**Comment by JohnEmad** [comment]
Hi, I really like blazor-state and how it sets on top of MediatR, but if we could implement something like IStateSelector in Fluxor https://github.com/mrpmorris/Fluxor/issues/221#issue-1039711280 

that would be really great

**Comment by StevenTCramer** [comment]
@szalapski @JohnEmad @zewa666 @petersondrew 

TimeWarp.State 11.0.0 is very close.  I pushed up Beta-60 today.   Rebranded from blazor-state.

I have addressed this issue with what I believe to be an elegant solution.

ITimeWarpStateComponent now has 

`bool ShouldReRender(Type stateType) => true;`

And the store supports previousState.

so now one can  do the following:

```cs
public override bool ShouldReRender(Type stateType)
  {
    return
      ShouldReRender<ApplicationState>(stateType, previousState => previousState.Version != Version)
      || ShouldReRender<ActionTrackingState>(stateType, previousState => previousState.IsActive != IsActive)
      || base.ShouldReRender(stateType);
  }
```
When any particular state changes the `RenderSubscriptionsPostProcessor`  will first call ShouldReRender passing the type of the state that has changed.  The Store now exposes the previous state which makes the above possible.

As opposed to the Blazor method  `ShouldRender` where if you implement it you have to cover all possible scenarios.  This `ShouldReRender` is scoped to the slice of state that changed and you can return false to reduce the number of ReRenders.

**Comment by szalapski** [comment]
One note: "Re"is a prefix and not a word, so by the rules of most coding standards, I'd advocate for "ShouldRerender" instead.

**Comment by szalapski** [comment]
I will try this out soon, hopefully.

**Comment by StevenTCramer** [comment]
> One note: "Re" is a prefix and not a word, so by the rules of most coding standards, I'd advocate for "ShouldRerender" instead.

`ShouldRender`
`ShouldRerender`
`ShouldReRender`

I was going for emphasis trying to  make it stand out... "Re"
`Should_Rerender`
`ShouldRerenderThisAintTheBlazorOne` :P

So you think `ShouldRerender`   I'm in beta still so I can change it now.

**Comment by StevenTCramer** [comment]
https://x.com/balajis/status/1815175248322654506

How funny.

**Comment by StevenTCramer** [comment]
More updates.  Now one can assign RenderTiggers with Expressions as below.

```
  protected override void OnInitialized()
  {
    RegisterRenderTrigger<CounterState>(p => p.Count);
    base.OnInitialized();
  }
```
